/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.analysiswindow;

import com.sun.tools.visualvm.charts.ChartFactory;
import com.sun.tools.visualvm.charts.SimpleXYChartDescriptor;
import com.sun.tools.visualvm.charts.SimpleXYChartSupport;
import java.awt.LayoutManager;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
//import org.LiveGraph.LiveGraph;

/**
 *
 * @author bmoths
 */
public class StripChart extends javax.swing.JPanel {

    private SimpleXYChartSupport simpleXYChartSupport;

    /**
     * Creates new form StripChart
     */
    public StripChart() {
        initComponents();
        repaint();
    }

    public void displayNewChart(String variableName) {
        simpleXYChartSupport = createSimpleXYChartSupport(variableName);
        showChart();
    }

    private SimpleXYChartSupport createSimpleXYChartSupport(String variableName) {
        SimpleXYChartDescriptor descriptor = SimpleXYChartDescriptor.decimal(0, false, 500);
        descriptor.addLineFillItems(variableName);
        descriptor.setYAxisDescription(variableName);
        return ChartFactory.createSimpleXYChart(descriptor);
    }

    private GroupLayout getGroupLayout() {
        LayoutManager layoutManager = getLayout();
        return (GroupLayout)layoutManager;
    }

    private JComponent getChart() {
        return simpleXYChartSupport.getChart();
    }

    private void showChart() {
        JComponent chart = getChart();
        GroupLayout groupLayout = getGroupLayout();
        groupLayout.replace(dummyPnl, chart);
        chart.setVisible(true);
    }

    public void addValue(int value) {
        simpleXYChartSupport.addValues(System.currentTimeMillis(), new long[]{value});
    }

    public void addTimeStampedValue(int timeStamp, int value) {
        simpleXYChartSupport.addValues(timeStamp, new long[]{value});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dummyPnl = new javax.swing.JPanel();

        javax.swing.GroupLayout dummyPnlLayout = new javax.swing.GroupLayout(dummyPnl);
        dummyPnl.setLayout(dummyPnlLayout);
        dummyPnlLayout.setHorizontalGroup(
            dummyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dummyPnlLayout.setVerticalGroup(
            dummyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dummyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dummyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dummyPnl;
    // End of variables declaration//GEN-END:variables
}
